version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    depends_on:
      - db
    environment:
      DATABASE_URL: "jdbc:postgresql://db:5432/${POSTGRES_DB}"
      DATABASE_USER: "${POSTGRES_USER}"
      DATABASE_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "8082:8082"

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile.webapp
    depends_on:
      - backend
    ports:
      - "8080:80"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/certs
    ports:
      - "443:443"
    depends_on:
      - webapp

volumes:
  db_data: