FROM node:14 as build

WORKDIR /app

RUN git clone https://github.com/traccar/traccar-web.git .
RUN npm install
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]