version: '3'

services:
  traccar:
    build:
      context: .
      dockerfile: Dockerfile.traccar
    ports:
      - "${TRACCAR_PORT}:8082"
    volumes:
      - traccar-logs:/opt/traccar/logs
      - traccar-data:/opt/traccar/data
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - traccar

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "${HTTPS_PORT}:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${CERTS_PATH}:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - traccar

volumes:
  traccar-logs:
  traccar-data:
  mysql-data: