# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ~/traccar/backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "8082:8082"

  webapp:
    build:
      context: ~/traccar/webapp
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"

  nginx:
    image: nginx:alpine
    volumes:
      - ~/traccar/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/traccar/certs:/etc/ssl/certs
    ports:
      - "443:443"
    depends_on:
      - webapp

volumes:
  db_data: