version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-traccar}
      POSTGRES_USER: ${POSTGRES_USER:-traccar}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-traccar}
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    depends_on:
      - db
    environment:
      DATABASE_URL: "${DATABASE_URL:-jdbc:postgresql://db:5432/traccar}"
      DATABASE_USER: "${DATABASE_USER:-traccar}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD:-traccar}"
    ports:
      - "8082:8082"
    restart: unless-stopped

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile.webapp
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/ssl/certs
    ports:
      - "443:443"
    depends_on:
      - webapp
    restart: unless-stopped

volumes:
  db_data: