version: '3'

services:
  traccar:
    build:
      context: .
      dockerfile: Dockerfile.traccar
    ports:
      - "8082:8082"
    volumes:
      - traccar-logs:/opt/traccar/logs
      - traccar-data:/opt/traccar/data
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - traccar

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: traccar
      MYSQL_USER: traccar
      MYSQL_PASSWORD: traccarpassword
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - traccar

volumes:
  traccar-logs:
  traccar-data:
  mysql-data: