FROM node:18-alpine as builder
WORKDIR /app/traccar/traccar-web
COPY . .
RUN npm install && npm run build

FROM nginx:alpine
COPY --from=builder /app/traccar/traccar-web/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]