FROM node:18-alpine as builder
RUN apk add --no-cache git
WORKDIR ~/traccar/webapp
RUN git clone --recursive https://github.com/traccar/traccar.git .
WORKDIR ~/traccar/webapp/traccar-web
RUN npm install && npm run build
RUN ls -la dist
FROM nginx:alpine
COPY --from=builder ~/traccar/webapp/traccar-web/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]